export const achievements = [
  {
    year: "2025",
    title: "SIH 2025 Finalist",
    org: "Smart India Hackathon · Government of India",
    body: "Selected as a national finalist among thousands of teams, building a working prototype under a 36-hour deadline alongside a cross-functional team.",
    icon: "trophy",
    metric: "Top 1%",
    metricLabel: "of national teams",
    featured: true,
  },
  {
    year: "2026",
    title: "Coding Club President",
    org: "NIT Durgapur",
    body: "Elected to lead the college coding club — organized hackathons and DSA contests, mentored juniors, and ran technical events across campus.",
    icon: "crown",
    metric: "500+",
    metricLabel: "students led",
  },
  {
    year: "2026",
    title: "Software Development Intern",
    org: "VS Arogya Meda Pvt. Ltd.",
    body: "Shipped features on a production full-stack codebase, working directly with the engineering team on real user-facing releases.",
    icon: "briefcase",
    metric: "Prod",
    metricLabel: "codebase shipped",
  },
  {
    year: "2024",
    title: "Competitive Programmer",
    org: "Self-Driven",
    body: "Solved consistently across DSA platforms while building the fundamentals that later powered every full-stack project shipped since.",
    icon: "code",
    metric: "500+",
    metricLabel: "problems solved",
  },
];
