export const projects = [
  {
    slug: "vyapar",
    index: "01",
    name: "Vyapar",
    year: "2025",
    problem: "Retailers were reconciling stock by hand across three spreadsheets.",
    body: "A multi-tenant inventory and billing platform. Real-time stock ledger, GST-compliant invoicing, and a reconciliation view that collapses three sources into one. Built the schema, the API, and the dashboard.",
    stack: ["React", "Node", "PostgreSQL", "Redis", "Docker"],
    role: "Full stack — solo",
    link: "#",
    image: "https://picsum.photos/seed/vyapar/1200/800",
  },
  {
    slug: "pulse",
    index: "02",
    name: "Pulse",
    year: "2024",
    problem: "Support agents kept losing context when a chat got handed off.",
    body: "Real-time collaboration layer with presence, typing indicators, and shared cursors. Socket.io over a Redis pub/sub backbone so it scales past one node. Optimistic UI with conflict reconciliation.",
    stack: ["React", "Socket.io", "Redis", "Express"],
    role: "Full stack",
    link: "#",
    image: "https://picsum.photos/seed/pulse/1200/800",
  },
  {
    slug: "orbit",
    index: "03",
    name: "Orbit",
    year: "2024",
    problem: "Nobody knew which service was actually deployed on Friday evening.",
    body: 'A deployment dashboard that pulls from GitHub Actions and shows what is live, where, and who shipped it. Timeline view, rollback trigger, and a Slack alert when a deploy sits in "pending" too long.',
    stack: ["Next.js", "GitHub API", "PostgreSQL", "Vercel"],
    role: "Full stack",
    link: "#",
    image: "https://picsum.photos/seed/orbit/1200/800",
  },
  {
    slug: "quill",
    index: "04",
    name: "Quill",
    year: "2023",
    problem: "Writing docs meant switching between an editor, a preview, and a terminal.",
    body: "A markdown editor with live preview, local-first storage, and a command palette that runs shell snippets straight from a code block. Offline-capable via IndexedDB.",
    stack: ["React", "IndexedDB", "Node", "Electron"],
    role: "Full stack — solo",
    link: "#",
    image: "https://picsum.photos/seed/quill/1200/800",
  },
];
